### ISSUE TITLE
Sometimes pasting code pastes to a completely different location.

### ISSUE THREAD

**Issue by rickmacgillis** [eclipse-pdt/pdt#114]
**Describe the bug**
Sometimes pasting code pastes to a completely different location. See video.

**Describe the eclipse environment**
Version: 2021-03 (4.19.0)
Build id: 20210312-0638

**Describe your system**
 - OS: Linux Mint 20.2
 - Version 20.2

**To Reproduce**
See video below.

**Expected behavior**
Paste only to the location specified by the cursor or highlighting.

**Screenshots**
See this video of the problem. https://www.loom.com/share/62925586eb5a4094b2b5077e75584165

**Comment by pounard** [comment]
It actually happens to me sometime, and I never managed to reproduce it ! Thanks for sharing this video.

**Comment by pounard** [comment]
It happened that I still occasionally reproduce it, but most of the time, it's because I hit CTRL (for pasting) and accidentally click with my mouse on a Symbol (which navigates to it), then I hit "V" which pastes at the position I accidentally navigated to).

Sounds stupid, it's a finger problem, and it also happens to me sometime in some other editors...

**Comment by rickmacgillis** [comment]
For me this isn't a finger issue.

**Comment by pounard** [comment]
Yes I remember that your screencap was pertinent, but it's not online anymore... Could you reproduce it ?

**Comment by rickmacgillis** [comment]
Unfortunately not. It seems that the Eclipse PDT team is ignoring this bug since August, so there's no value in doing so. If a maintainer requests it, I'll create a new video.

**Comment by zulus** [comment]
This is not PDT bug itself but SSE (same problems in XML and CSS editors), document is not always correctly synchronized with UI. Same problems appear sometimes after ctrl+z, etc... Since at least 10 years none touched this on WTP side, i have to drop entire WTP support. Marking as wontfix (it's nothing to do on PDT side)
