### ISSUE TITLE
error inexistent listed

### ISSUE THREAD

**Issue by RodrigoAliotti** [eclipse-pdt/pdt#176]
**Describe the bug**
When write : function( #[SensitiveParameter]  the eclipse return a problem: SensitiveParameter cannot be resolved to a type	

**Describe the eclipse environment**
Eclipse Version 2023-06 (4.28.0), PDT version (8.0.0.202306050832)

**Describe your system**
 - OS: [linux]
 - Version [6.1.31-2-MANJARO]
 - PHP Version (8.2.6)
 
**To Reproduce**
1. Create new php file
2. write new function: function  test(#[SensitiveParameter] String $aValue){ echo ' test'; }
3. save file
4
![Captura de tela_2023-06-16_12-17-45](https://github.com/eclipse-pdt/pdt/assets/87990789/a631ebe9-d05b-407a-82e2-9b4592f3c10b)
.error is reported in problems in tab of eclipse

**Comment by mlocati** [comment]
At the beginning of your PHP file you define a namespace, right?
If so, it's not a problem of PDT: you are telling PHP to use the `SensitiveParameter` attribute defined in your namespace.
If you want to refer to the `SensitiveParameter` defined in the root namespace (that is, the one that comes with PHP 8.2), you have to use `#[\SensitiveParameter]` instead of `#[SensitiveParameter]`.

**Comment by zulus** [comment]
If didn’t define Classes\SensitiveParameter or didn’t import \SensitiveParameter error is correct
